title: Santino Navaroli
logo: assests/img/Professional_Profile2-modified.png
description: Cybersecurity (B.S), University of North Georgia; Pursuing a minor in Computer Science
show_downloads: false
theme: jekyll-theme-minimal
